### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by kifle23** [kifle23/recipe-app#9]
In this project, we are 2 coding partners @deniodev and @kifle23.

The project task list (Kanban board) can be found [here](https://github.com/users/kifle23/projects/7).

It is a recipe app that keeps track of all your recipes and ingredients. It will allow you to save ingredients, and keep track of what you have, and create recipes.

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info✔️
- Tasks distributed equally ✔️  

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kifle23** [comment]
Thank you @gemmen29 🙏
